Repository Whiplash-Robotics/Whiplash-Aimbot, pull requests merged in 2025-03, with the labels that each got.

#27 feat(docs): add cv page to docs and include daniel in contributors
  README.md
  documentation/content/docs/index.mdx
  documentation/content/docs/meta.json
  documentation/content/docs/research-development-cv/Figure_1.png
  documentation/content/docs/research-development-cv/meta.json
  documentation/content/docs/research-development-cv/modelSelection.mdx
  documentation/tailwind.config.js
  documentation/utils/Figure_1.png
  documentation/utils/benchmarks.json
  documentation/utils/graph.py
Labels: Status: Reviewed

#40 chore: move .gitattributes to root
  .gitattributes
  game_environment/.gitattributes
Labels: Status: Reviewed

#43 fix: update .gitattributes for proper language detection
  .gitattributes
Labels: Status: Done

#50 feat: update game init and mouse docs
  documentation/app/(docs)/[[...slug]]/page.tsx
  documentation/content/docs/design/meta.json
  documentation/content/docs/design/motor-cage.mdx
  documentation/content/docs/design/motorcage.png
  documentation/content/docs/game-dev/initialization.mdx
  documentation/content/docs/research-development-hardware/electronic-parts/mouse.mdx
  documentation/content/docs/research-development-software/engine.mdx
Labels: Status: Done

#52 feat: deploy test
  documentation/content/docs/index.mdx
  documentation/netlify.toml
  documentation/package-lock.json
  documentation/package.json
Labels: Status: In Progress

#56 feat: add netlify deployments to gh
  .github/update-github-deployments.yaml
Labels: Status: Done

#57 feat(docs): update timing-belt docs
  documentation/content/docs/research-development-cv/Figure_1.png
  documentation/content/docs/research-development-hardware/mechanical-parts/timing-belt.mdx
  documentation/utils/Figure_1.png
Labels: Status: In Progress

#58 feat(docs): add motor controller docs
  documentation/content/docs/research-development-hardware/electronic-parts/motor-controller.mdx
  documentation/content/docs/research-development-hardware/electronic-parts/power-supply.mdx
Labels: Status: In Progress
